####################################
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/telangsachin/udemy-rsmortgage-config-repository-1
          searchPaths: udemy-rsmortgage-customer-service
          username: telangsachin
          password: India@2017
